nodeLinker: node-modules

packageExtensions:
  "@tiptap/react@*":
    peerDependenciesMeta:
      "@tiptap/core":
        optional: true

  "@tiptap/pm@*":
    peerDependenciesMeta:
      "@tiptap/core":
        optional: true

  "@tiptap/extension-list-item@*":
    peerDependenciesMeta:
      "@tiptap/core":
        optional: true

  "@tiptap/extension-text-style@*":
    peerDependenciesMeta:
      "@tiptap/core":
        optional: true
