import { MantineProvider, ColorSchemeScript } from '@mantine/core'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import '@mantine/core/styles.css'
import './globals.css'
import TopBar from '@/components/TopBar/TopBar'
import { theme } from '../theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <UserProvider>
        <body className={inter.className}>
          <MantineProvider theme={theme}>
            <TopBar />
            {children}
          </MantineProvider>
        </body>
      </UserProvider>
    </html>
  )
}
