import { MantineProvider, ColorSchemeScript } from '@mantine/core'
import type { Metadata } from 'next'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import '@mantine/core/styles.css'
import './globals.css'
import { theme } from '../theme'
import AppShell from '@/components/AppShell/AppShell'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <UserProvider>
        <body>
          <MantineProvider theme={theme}>
            <AppShell>
              {children}
            </AppShell>
          </MantineProvider>
        </body>
      </UserProvider>
    </html>
  )
}
