// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat, faker } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
copycat.setHashKey("uuUR3my/gSrr9fR/");
export default defineConfig({
  transform: {
    $mode: "unsafe",
    public: {
      Debate({ row }) {
        return {
          topic: copycat.city(row.topic).slice(0, 255),
        };
      },
      User({ row }) {
        return {
          email: copycat.email(row.email),
        };
      },
      _prisma_migrations({ row }) {
        return {
          checksum: copycat.scramble(row.checksum),
        };
      },
    },
  },
  subset: {
    enabled: true,
    version: "3",
    targets: [
      {
        table: "public.User",
        rowLimit: 100,
      },
    ],
    keepDisconnectedTables: false,
    followNullableRelations: true,
    maxCyclesLoop: 0,
    eager: false,
    taskSortAlgorithm: "children",
  },
});
