export interface LogicalFallacy {
  id: string
  name: string
  description: string
  example: string
  pattern: string
  recommendation: string
  url: string
}

export const logicalFallaciesData: LogicalFallacy[] = [
  {
    id: 'ad-hominem-001',
    name: 'Ad Hominem',
    description: "<p>An ad hominem fallacy (Latin for \"to the person\") means attacking the person making an argument, instead of the argument itself. It's like saying an idea is bad because you don't like someone's hat, which doesn't address the idea's logic.</p>",
    example: '<p>Instead of discussing if a new school rule is fair, someone says, "Well, the student who proposed it is always late for class, so it must be a bad idea!" This attacks the student, not the rule itself.</p>',
    recommendation: "<p>If you're tempted to attack someone personally instead of their idea, remember it weakens your own stance. Focus on the argument's facts and logic, not the person, for a stronger and more respectful discussion.</p>",
    pattern: "(\\b(you're|he's|she's|they're)\\s+(just|only|so|a(n)?)\\s+(stupid|idiot|fool|biased|liar|lazy|crazy|ignorant)\\b|\\b(your|his|her|their)\\s+(opinion|argument|point|idea)\\s+is\\s+(worthless|invalid|stupid|silly)\\s+because\\s+(you|he|she|they))",
    url: 'https://en.wikipedia.org/wiki/Ad_hominem',
  },
  {
    id: 'straw-man-002',
    name: 'Straw Man Fallacy',
    description: "<p>A straw man fallacy occurs when someone misrepresents or exaggerates an opponent's argument to make it easier to attack. It's like fighting a scarecrow instead of the real person because the scarecrow is easier to knock down.</p>",
    example: "<p>If someone says, \"We should spend a bit more on school art programs,\" and another replies, \"So you want to waste all our money on paint and cut sports entirely? That's ridiculous!\" The reply attacks an extreme, unstated version of the original idea.</p>",
    recommendation: "<p>Before arguing, ensure you understand your opponent's actual position, not a twisted version. Attacking a misrepresentation (a straw man) is unfair and doesn't lead to productive discussion; address their real points instead.</p>",
    //"pattern": "(so\\s+you(?:'re|r)\\s+(?:saying|arguing|claiming|implying)|so\\s+what\\s+you(?:'re|r)\\s+really\\s+saying\\s+is|if\\s+I\\s+understand\\s+you\\s+correctly,\\s+you\\s+think)\\s+(that\\s+)?(.+)(\\?|\\bthat's ridiculous\\b|\\bthat's absurd\\b)",
    pattern: "(so\\s+you(?:'re|r)\\s+(?:saying|arguing|claiming|implying)|so\\s+what\\s+you(?:'re|r)\\s+really\\s+saying\\s+is|if\\s+I\\s+understand\\s+you\\s+correctly,\\s+you\\s+think)\\s+(that\\s+)?(.+)(\\?)",
    url: 'https://en.wikipedia.org/wiki/Straw_man',
  },
  {
    id: 'appeal-to-ignorance-003',
    name: 'Appeal to Ignorance (Argumentum ad Ignorantiam)',
    description: "<p>This fallacy claims something is true because it hasn't been proven false, or false because it hasn't been proven true. Lack of proof isn't proof of the opposite; it just means we don't know for sure.</p>",
    example: "<p>Someone might say, \"No one has ever proven ghosts *don't* exist, so they must be real!\" Or, \"We haven't found aliens yet, so they definitely don't exist.\" Both assume a conclusion based on a lack of evidence.</p>",
    recommendation: "<p>Avoid claiming something is true or false just because there's no proof for the other side. Acknowledge when evidence is missing instead of jumping to conclusions based on ignorance.</p>",
    pattern: "(\\b(no\\sone|nobody|nobody\'s|noone|no\\sone\'s)\\s+(has\\s+)?(ever\\s+)?proven\\s+(that\\s+)?.{2,40}\\s+is(n't)?\\s+true\\b|\\bthere's\\s+no\\s+evidence\\s+for\\s+X,\\s+so\\s+X\\s+must\\s+be\\s+false\\b|\\b(since|because)\\s+you\\s+can't\\s+prove\\s+X\\s+is\\s+false,\\s+it\\s+must\\s+be\\s+true\\b)",
    url: 'https://en.wikipedia.org/wiki/Argument_from_ignorance',
  },
  {
    id: 'false-dilemma-004',
    name: 'False Dilemma / False Dichotomy',
    description: "<p>This fallacy presents only two options as if they are the only possibilities, when in fact more options exist. It unfairly limits choices by creating an \"either/or\" situation that isn't necessarily true.</p>",
    example: "<p>\"You're either with us, or you're against us!\" This statement ignores the possibility of being neutral, agreeing with parts of both sides, or having a completely different stance.</p>",
    recommendation: "<p>Don't limit an issue to just two extreme choices if more options are available. Presenting a false dilemma can mislead; aim for a fair representation of all reasonable possibilities.</p>",
    pattern: "(\\b(either\\s+you're|it's\\s+either)\\s+.+\\s+or\\s+.+\\b(there\\s+are\\s+no\\s+other\\s+options|it's\\s+that\\s+simple)|\\b(you\\s+must\\s+choose|the\\s+only\\s+choice\\s+is)\\s+A\\s+or\\s+B\\b)",
    url: 'https://en.wikipedia.org/wiki/False_dilemma',
  },
  {
    id: 'slippery-slope-005',
    name: 'Slippery Slope',
    description: "<p>This fallacy argues that if one small step is taken, it will inevitably lead to a chain of negative events, usually ending in some disaster. It suggests we can't stop the slide once it starts, often without enough evidence for the chain reaction.</p>",
    example: "<p>\"If we let students use phones in the library, soon they'll be using them in class, then during tests, and then no one will learn anything!\" This assumes a worst-case chain of events without proof.</p>",
    recommendation: '<p>Avoid arguing that a small action will definitely lead to a terrible outcome unless you have strong evidence for each step in the chain. Exaggerating consequences this way is a slippery slope fallacy.</p>',
    pattern: "(\\bif\\s+we\\s+(allow|let|do)\\s+A,\\s+then\\s+B\\s+will\\s+happen,\\s+and\\s+then\\s+C,\\s+and\\s+eventually\\s+Z\\b|\\b(it's\\s+a\\s+slippery\\s+slope|once\\s+we\\s+start|where\\s+does\\s+it\\s+end)\\b)",
    url: 'https://en.wikipedia.org/wiki/Slippery_slope',
  },
  {
    id: 'circular-argument-006',
    name: 'Circular Argument (Begging the Question)',
    description: "<p>A circular argument is when an argument's conclusion is just a restatement of one of its starting points (premises). It's like saying \"X is true because X is true,\" so it doesn't actually prove anything new.</p>",
    example: '<p>"This book is well-written because the author is a good writer." The reason (good writer) and the claim (well-written book) are essentially the same thing, offering no real evidence.</p>',
    recommendation: "<p>Ensure your reasons for a claim provide new information and support, rather than just restating the claim in different words. A circular argument doesn't persuade because it offers no external proof.</p>",
    pattern: "(\\b((is|it\'s)\\s+true\\s+because\\s+.{2,20}\\s+is\\s+true)|(is\\s+true|good|right)\\s+because\\s+the\\s+(bible|scripture|book|law|rules)\\s+(says|say)\\s+so,\\s+and\\s+the\\s+(bible|scripture|book|law|rules)\\s+is\\s+true\\b|\\b(obviously|clearly)\\s+.{2,20},\\s+therefore\\s+.{2,50}\\b)",
    url: 'https://en.wikipedia.org/wiki/Begging_the_question',
  },
  {
    id: 'hasty-generalization-007',
    name: 'Hasty Generalization',
    description: "<p>This fallacy involves drawing a broad conclusion based on a small or unrepresentative sample of evidence. It's like judging a whole group based on only one or two examples you've seen.</p>",
    example: '<p>"I met two rude people from Cityville, so everyone from Cityville must be rude." This conclusion about an entire city is based on very limited personal experience.</p>',
    recommendation: '<p>Avoid making sweeping statements about a whole group based on just a few instances. Ensure your conclusions are supported by sufficient and representative evidence to avoid a hasty generalization.</p>',
    pattern: '(\\b(I\\s+saw|I\\s+met|my\\s+friend)\\s+(one|two|a\\s+few)\\s+X\\s+and\\s+they\\s+were\\s+Y,\\s+so\\s+all\\s+X\\s+are\\s+Y\\b|\\b(everyone|all|nobody|always|never)\\s+from\\s+X\\s+is\\s+Y\\b.*based on limited experience)',
    url: 'https://en.wikipedia.org/wiki/Hasty_generalization',
  },
  {
    id: 'red-herring-008',
    name: 'Red Herring',
    description: "<p>A red herring is a distraction tactic where someone introduces an irrelevant topic into an argument to divert attention from the main issue. It's named after a strong-smelling fish that was used to distract hunting dogs from a trail.</p>",
    example: '<p>When asked about fixing potholes, a politician might say, "The real issue is the beautiful new park we just opened!" This changes the subject from roads to something unrelated but positive.</p>',
    recommendation: "<p>If you want to make a strong argument, stick to the main topic. Introducing irrelevant information (a red herring) to distract can make it seem like you can't address the actual issue.</p>",
    pattern: "(\\b(that's\\s+not\\s+the\\s+real\\s+issue|what\\s+about|but\\s+let's\\s+talk\\s+about|the\\s+more\\s+important\\s+question\\s+is)\\s+[^\\.\\?]+\\b(when the new topic is irrelevant))",
    url: 'https://en.wikipedia.org/wiki/Red_herring',
  },
  {
    id: 'tu-quoque-009',
    name: 'Tu Quoque ("You too")',
    description: "<p>Tu quoque is a fallacy where someone tries to discredit an argument by pointing out that the person making it is acting inconsistently with their own advice (hypocrisy). While hypocrisy might be true, it doesn't automatically make their argument wrong.</p>",
    example: "<p>If a doctor advises a patient to stop smoking, and the patient replies, \"But you smoke too, so your advice is worthless!\" The doctor's habit doesn't change the health risks of smoking.</p>",
    recommendation: "<p>Avoid dismissing someone's argument just because they might be acting inconsistently. While you can point out hypocrisy, remember to also address the merits of their actual point (the tu quoque fallacy focuses on the person, not the argument's validity).</p>",
    pattern: "(\\b(you\\s+too|you\\s+also|look\\s+who's\\s+talking|practice\\s+what\\s+you\\s+preach)\\b|\\b(how\\s+can\\s+you\\s+say\\s+X\\s+when\\s+you\\s+do\\s+Y)\\b)",
    url: 'https://en.wikipedia.org/wiki/Tu_quoque',
  },
  {
    id: 'post-hoc-010',
    name: 'Post Hoc Ergo Propter Hoc (False Cause)',
    description: "<p>This Latin phrase means \"after this, therefore because of this.\" It's a fallacy where someone assumes that because one event happened after another, the first event must have caused the second, even if there's no real connection.</p>",
    example: "<p>\"I wore my lucky socks to the game, and we won! My socks must have made us win.\" The win came after wearing the socks, but the socks didn't cause the win.</p>",
    recommendation: "<p>Don't assume that just because B happened after A, A must have caused B. Look for actual evidence of a causal link before making such a claim, otherwise you're committing a false cause fallacy.</p>",
    pattern: '(\\b(after\\s+I\\s+|ever\\s+since)\\s+.{4,50},\\s+Y\\s+happened,\\s+so\\s+X\\s+must\\s+have\\s+caused\\s+Y\\b|\\b(correlation\\s+does\\s+not\\s+imply\\s+causation\\b.*when violated))',
    url: 'https://en.wikipedia.org/wiki/Post_hoc_ergo_propter_hoc',
  },
  {
    id: 'appeal-to-authority-011',
    name: 'Appeal to Authority (Argumentum ad Verecundiam)',
    description: "<p>This fallacy happens when someone claims something is true because an authority figure said it, even if that authority isn't an expert on the specific topic. True authority should be relevant to the subject at hand.</p>",
    example: '<p>"My favorite actor said this brand of vitamins is the best, so it must be true." The actor is an expert in acting, not nutrition, making their endorsement on vitamins potentially unreliable.</p>',
    recommendation: "<p>When citing an authority, ensure they are a genuine expert on the specific topic you're discussing. Appealing to an irrelevant authority doesn't strengthen your argument and can be misleading.</p>",
    pattern: '(\\b(Dr\\.|Professor|Scientist|Expert|Celebrity)\\s+X\\s+says\\s+Y\\s+is\\s+true,\\s+so\\s+it\\s+must\\s+be\\s+true\\b(?!.*\\b(in their field of expertise|on the topic of)\\b))',
    url: 'https://en.wikipedia.org/wiki/Argument_from_authority',
  },
  {
    id: 'bandwagon-fallacy-012',
    name: 'Bandwagon Fallacy',
    description: "<p>The bandwagon fallacy argues that something must be true or good because many people believe it or are doing it. Popularity alone doesn't make something right or correct.</p>",
    example: "<p>\"Everyone is buying these new shoes, so they must be the best shoes available!\" The fact that many people buy them doesn't prove their quality or suitability for everyone.</p>",
    recommendation: "<p>Don't assume an idea is correct just because it's popular. Focus on the evidence and reasoning behind the idea itself, rather than how many people support it (joining the bandwagon).</p>",
    pattern: "(\\b(everyone|everyone\'s|everybody|everybody\'s|most\\s+people|the\\s+majority)\\s+(believes|doing|says|agrees)\\b)",
    url: 'https://en.wikipedia.org/wiki/Argumentum_ad_populum',
  },
  {
    id: 'appeal-to-emotion-013',
    name: 'Appeal to Emotion',
    description: "<p>This fallacy involves trying to win an argument by manipulating someone's emotions (like fear, pity, or anger) instead of using logic or facts. Strong feelings don't make an argument valid.</p>",
    example: "<p>\"You must donate to this cause; think of all the sad, helpless puppies!\" This uses pity for puppies to persuade, rather than explaining the cause's effectiveness or how donations are used.</p>",
    recommendation: '<p>While emotions are important, try to support your arguments with facts and logic, not just by trying to make people feel a certain way. Emotional appeals can obscure the real issues.</p>',
    pattern: "(\\b(think\\s+of\\s+the\\s+children|poor\\s+helpless|if\\s+you\\s+don't\\s+agree,\\s+something\\s+terrible\\s+will\\s+happen|you\\s+should\\s+be\\s+ashamed|makes\\s+me\\s+so\\s+angry)\\b(?!.*\\b(followed by logical reasoning)\\b))",
    url: 'https://en.wikipedia.org/wiki/Appeal_to_emotion',
  },
  {
    id: 'equivocation-014',
    name: 'Equivocation',
    description: "<p>Equivocation is a fallacy where a word or phrase with multiple meanings is used in a way that shifts meaning during the argument, leading to a misleading conclusion. It's like a verbal sleight of hand.</p>",
    example: "<p>\"The sign said 'Fine for parking here,' and since it was fine, I parked there.\" This confuses \"fine\" as a penalty with \"fine\" as meaning acceptable or okay.</p>",
    recommendation: '<p>Be clear and consistent with the meaning of your words, especially if they can have multiple interpretations. Shifting meanings (equivocation) can confuse the issue and make your argument unsound.</p>',
    pattern: "(\\b(X\\s+means\\s+A,\\s+but\\s+also\\s+X\\s+means\\s+B,\\s+therefore\\s+A\\s+is\\s+B\\s+in\\s+a\\s+confusing\\s+way)|\\b(using\\s+a\\s+word\\s+like\\s+'fine'\\s+or\\s+'right'\\s+with\\s+two\\s+different\\s+meanings\\s+in\\s+the\\s+same\\s+argument)\\b)",
    url: 'https://en.wikipedia.org/wiki/Equivocation',
  },
  {
    id: 'genetic-fallacy-015',
    name: 'Genetic Fallacy',
    description: "<p>The genetic fallacy judges an idea or thing based on its origin or history, rather than its current merits or qualities. Where something comes from doesn't automatically determine its worth now.</p>",
    example: "<p>\"That new phone can't be any good; it's made by the same company that made that terrible toaster 10 years ago!\" The company's past failure with a different product doesn't mean the new phone is bad.</p>",
    recommendation: '<p>Evaluate ideas and products based on their current features, evidence, and performance, not just on their origin or source. The genetic fallacy unfairly dismisses or accepts things based on their history.</p>',
    pattern: "(\\b(comes|came)\\s+from+(\\s+a|\\s+an)?(\\s+bad|\\s+good|X)\\s+(company|place|source|stock|upgringing),\\s+so\\s+(it|it\'s|they|they\'ve)\\s+(certainly|gotta|must)\\b|\\b(you\\s+only\\s+say\\s+that\\s+because\\s+of\\s+your\\s+upbringing|background)\\b)",
    url: 'https://en.wikipedia.org/wiki/Genetic_fallacy',
  },
  {
    id: 'no-true-scotsman-016',
    name: 'No True Scotsman Fallacy',
    description: "<p>This fallacy is a way of protecting a generalization from counterexamples by changing the definition to exclude the counterexample. It's like saying, \"No *true* member of this group would do that!\"</p>",
    example: '<p>Person A: "No Scotsman puts sugar on his porridge." Person B: "But my friend Angus is a Scotsman, and he puts sugar on his porridge." Person A: "Ah, yes, but no *true* Scotsman puts sugar on his porridge."</p>',
    recommendation: '<p>Avoid redefining a group or category just to exclude counterexamples that challenge your generalization. This "No True Scotsman" move makes your claim unfalsifiable and avoids genuine discussion.</p>',
    //"pattern": "(\\b(no\\s+true\\s+X\\s+would\\s+do\\s+Y|a\\s+real\\s+X\\s+wouldn't\\s+Y)\\b(?!.*\\b(unless they had a good reason)\\b))",
    pattern: '(\\b(no\\s+(true|legit|real)\\s+.{2,30}\\s+would\\b))',
    url: 'https://en.wikipedia.org/wiki/No_True_Scotsman',
  },
  {
    id: 'burden-of-proof-017',
    name: 'Burden of Proof Fallacy (Onus Probandi)',
    description: '<p>This fallacy occurs when someone makes a claim but insists that others must prove it false, instead of providing evidence to support their own claim. The person making the claim usually has the responsibility (burden) to prove it.</p>',
    example: "<p>\"I believe invisible unicorns exist. Since you can't prove they *don't* exist, they must be real!\" The person claiming unicorns exist should provide evidence, not demand others disprove it.</p>",
    recommendation: '<p>If you make a claim, be prepared to support it with evidence. Shifting the burden of proof to others to disprove your unsubstantiated claim is a fallacy and an unfair tactic in an argument.</p>',
    pattern: "(\\b(I\\s+claim\\s+X,\\s+and\\s+you\\s+have\\s+to\\s+prove\\s+me\\s+wrong|prove\\s+that\\s+X\\s+isn't\\s+true|since\\s+you\\s+can't\\s+disprove\\s+X,\\s+X\\s+is\\s+true)\\b)",
    url: 'https://en.wikipedia.org/wiki/Burden_of_proof_(philosophy)',
  },
  {
    id: 'appeal-to-nature-018',
    name: 'Appeal to Nature',
    description: "<p>This fallacy argues that something is good because it's \"natural,\" or bad because it's \"unnatural.\" Whether something is natural or not doesn't automatically make it good or bad for us.</p>",
    example: '<p>"This medicine is made from all-natural herbs, so it must be safe and effective." Many natural things can be harmful (like poison ivy), and many unnatural things can be beneficial (like life-saving synthetic drugs).</p>',
    recommendation: "<p>Don't assume something's quality or safety based solely on whether it's labeled \"natural\" or \"unnatural.\" Evaluate things based on evidence of their actual effects and properties.</p>",
    pattern: "(\\b(it's\\s+natural,\\s+so\\s+it\\s+must\\s+be\\s+good|healthy|safe)\\b|\\b(it's\\s+unnatural|artificial|man-made),\\s+so\\s+it\\s+must\\s+be\\s+bad|harmful\\b)",
    url: 'https://en.wikipedia.org/wiki/Appeal_to_nature',
  },
  {
    id: 'anecdotal-fallacy-019',
    name: 'Anecdotal Fallacy',
    description: "<p>This fallacy uses a personal experience or an isolated example (an anecdote) as evidence for a broad claim, instead of using sound reasoning or scientific evidence. Personal stories can be illustrative but aren't usually enough to prove a general rule.</p>",
    example: "<p>\"My grandpa smoked his whole life and lived to be 90, so smoking isn't actually bad for you.\" This one personal story ignores the vast scientific evidence that smoking is harmful.</p>",
    recommendation: '<p>While personal stories can be compelling, avoid using them as the sole proof for a general claim. Look for broader evidence and data rather than relying only on anecdotes, which might not be representative.</p>',
    pattern: '(\\b(my\\s+(grandpa|friend|cousin|experience)|I\\s+know\\s+someone\\s+who)\\s+did\\s+X\\s+and\\s+Y\\s+happened,\\s+so\\s+X\\s+always\\s+leads\\s+to\\s+Y\\b|\\b(this\\s+one\\s+time|I\\s+heard\\s+a\\s+story)\\b(?!.*\\b(as an illustration, not proof)\\b))',
    url: 'https://en.wikipedia.org/wiki/Anecdotal_evidence',
  },
  {
    id: 'fallacy-fallacy-020',
    name: 'The Fallacy Fallacy (Argument from Fallacy)',
    description: '<p>This fallacy assumes that if an argument contains a logical fallacy, then its conclusion must be false. However, a bad argument for a true conclusion is still a bad argument, but the conclusion might still be true for other reasons.</p>',
    example: "<p>Person A makes a poor, fallacious argument for why the sky is blue. Person B says, \"Your argument was fallacious, therefore the sky isn't blue!\" The argument was bad, but the sky is indeed blue due to other scientific reasons.</p>",
    recommendation: "<p>If you spot a fallacy in someone's argument, it means their reasoning is flawed, but it doesn't automatically make their conclusion false. Point out the flawed reasoning, but don't assume the conclusion is wrong without further investigation.</p>",
    pattern: '(\\b(your\\s+argument\\s+for\\s+X\\s+is\\s+fallacious|contains\\s+a\\s+fallacy),\\s+therefore\\s+X\\s+is\\s+false\\b)',
    url: 'https://en.wikipedia.org/wiki/Argument_from_fallacy',
  },
  {
    id: 'appeal-to-tradition-021',
    name: 'Appeal to Tradition (Argumentum ad Antiquitatem)',
    description: "<p>This fallacy claims something is good or true simply because it's old, traditional, or has \"always been done this way.\" Age or tradition alone doesn't guarantee correctness or quality.</p>",
    example: "<p>\"We've always had our town festival on this date, so we shouldn't change it, even if it conflicts with a major holiday.\" This relies on tradition rather than practical reasons for the date.</p>",
    recommendation: "<p>Don't assume something is best just because it's traditional. Evaluate practices and ideas on their current merits and effectiveness, not just their age or history.</p>",
    pattern: "(\\b(it's\\s+tradition|we've\\s+always\\s+done\\s+it\\s+this\\s+way|this\\s+is\\s+how\\s+it's\\s+been\\s+for\\s+generations)\\s+so\\s+it\\s+must\\s+be\\s+(right|good|the\\s+best\\s+way)\\b)",
    url: 'https://en.wikipedia.org/wiki/Appeal_to_tradition',
  },
  {
    id: 'appeal-to-novelty-022',
    name: 'Appeal to Novelty (Argumentum ad Novitatem)',
    description: "<p>This fallacy argues that something is better or true simply because it is new or modern. Being new doesn't automatically make something superior to older alternatives.</p>",
    example: "<p>\"This new smartphone is the latest model, so it must be much better than last year's version.\" While new models often have improvements, being new isn't itself proof of superiority without specific reasons.</p>",
    recommendation: "<p>Avoid assuming something is superior just because it's new. Judge ideas or products on their actual features, performance, and evidence, not merely on their novelty.</p>",
    pattern: "(\\b(it's\\s+new|the\\s+latest|modern|up-to-date)\\s+so\\s+it\\s+must\\s+be\\s+(better|right|superior)\\b)",
    url: 'https://en.wikipedia.org/wiki/Appeal_to_novelty',
  },
  {
    id: 'composition-fallacy-023',
    name: 'Composition Fallacy',
    description: '<p>The composition fallacy assumes that what is true for individual parts of something must also be true for the whole thing. However, a group can have different properties than its individual members.</p>',
    example: "<p>\"Each player on this basketball team is an excellent athlete, therefore the team must be unbeatable.\" Individual skill doesn't guarantee perfect teamwork or an unbeatable team.</p>",
    recommendation: "<p>Don't assume that the characteristics of individual parts automatically apply to the entire whole. Consider how parts interact to form the whole, which might have different properties.</p>",
    pattern: '(\\b(each\\s+part|every\\s+member)\\s+of\\s+X\\s+has\\s+property\\s+Y,\\s+therefore\\s+X\\s+as\\s+a\\s+whole\\s+has\\s+property\\s+Y\\b)',
    url: 'https://en.wikipedia.org/wiki/Fallacy_of_composition',
  },
  {
    id: 'division-fallacy-024',
    name: 'Division Fallacy',
    description: "<p>The division fallacy is the opposite of the composition fallacy; it assumes that what is true for the whole must also be true for all of its individual parts. This isn't always the case.</p>",
    example: "<p>\"Our school is known for its excellent music program, so every student at our school must be a great musician.\" The overall program's quality doesn't mean every single student excels in music.</p>",
    recommendation: '<p>Avoid assuming that properties of a whole automatically apply to each of its individual parts. Recognize that parts can differ from the overall characteristics of the group or system.</p>',
    pattern: '(\\b(X\\s+as\\s+a\\s+whole\\s+has\\s+property\\s+Y,\\s+therefore\\s+each\\s+part|every\\s+member)\\s+of\\s+X\\s+must\\s+have\\s+property\\s+Y\\b)',
    url: 'https://en.wikipedia.org/wiki/Fallacy_of_division',
  },
  {
    id: 'guilt-by-association-025',
    name: 'Guilt by Association',
    description: "<p>This fallacy tries to discredit an idea or person by associating them with an unpopular or negatively viewed person or group. The association itself doesn't prove the idea or person is bad.</p>",
    example: "<p>\"You like that band? But a really mean celebrity also likes that band, so your taste in music must be bad.\" The celebrity's character doesn't logically affect the quality of the music or someone else's taste.</p>",
    recommendation: '<p>Evaluate ideas and people on their own merits, not by who or what they might be associated with. Discrediting by association is often an unfair tactic to avoid addressing the actual point.</p>',
    pattern: '(\\b(X\\s+is\\s+associated\\s+with\\s+Y,\\s+and\\s+Y\\s+is\\s+bad,\\s+therefore\\s+X\\s+is\\s+bad)\\b|\\b(you\\s+agree\\s+with|like\\s+the\\s+same\\s+thing\\s+as)\\s+(someone\\s+bad|a\\s+bad\\s+group)\\b)',
    url: 'https://en.wikipedia.org/wiki/Association_fallacy',
  },
  {
    id: 'poisoning-the-well-026',
    name: 'Poisoning the Well',
    description: "<p>This is a tactic where someone presents irrelevant negative information about a person beforehand to discredit whatever that person might say later. It 'poisons the well' so others are biased against their future arguments.</p>",
    example: '<p>"Before you hear my opponent speak, remember that he once failed a math test in 5th grade!" This irrelevant past event is used to make the audience doubt anything the opponent says, regardless of its merit.</p>',
    recommendation: "<p>Avoid using preemptive attacks on someone's character to discredit their future arguments. Focus on the arguments themselves, and be wary if someone tries to bias you against a speaker before they've even presented their case.</p>",
    pattern: "(\\b(before\\s+you\\s+listen\\s+to\\s+X|don't\\s+listen\\s+to\\s+X\\s+because)|(my\\s+opponent\\s+is\\s+a\\s+Y,\\s+so\\s+don't\\s+trust\\s+anything\\s+they\\s+say)\\b(?!.*\\b(with valid reasoning related to credibility on the topic)\\b))",
    url: 'https://en.wikipedia.org/wiki/Poisoning_the_well',
  },
  {
    id: 'moving-the-goalposts-027',
    name: 'Moving the Goalposts (Raising the Bar)',
    description: '<p>This fallacy occurs when someone changes the criteria for proof or success after an initial criterion has been met, making it harder or impossible for the opponent to satisfy the new demands.</p>',
    example: "<p>Person A: \"If you can show me one study that supports your claim, I'll believe you.\" Person B shows a study. Person A: \"Okay, but that's just one study. Now you need to show me five more, and they all have to be from the last year!\"</p>",
    recommendation: '<p>Establish clear and fair standards of proof at the beginning of a discussion and stick to them. Continuously changing the requirements (moving the goalposts) is an unfair way to avoid conceding a point.</p>',
    pattern: "(\\b(now\\s+you\\s+need\\s+to|that's\\s+not\\s+enough,\\s+you\\s+also\\s+have\\s+to|but\\s+what\\s+about)\\s+(a\\s+new\\s+or\\s+higher\\s+standard)\\b(?!.*\\b(when the new standard is reasonable and agreed upon)\\b))",
    url: 'https://en.wikipedia.org/wiki/Moving_the_goalposts',
  },
  {
    id: 'texas-sharpshooter-028',
    name: 'Texas Sharpshooter Fallacy',
    description: "<p>This fallacy occurs when someone cherry-picks data or focuses on similarities while ignoring differences to make an argument seem stronger. It's like shooting a barn wall and then drawing targets around the bullet holes.</p>",
    example: "<p>A psychic makes many vague predictions, and when one coincidentally seems to come true, they highlight it as proof of their powers, ignoring all the failed predictions. They focus only on the 'hits'.</p>",
    recommendation: '<p>Consider all relevant data and evidence, not just the pieces that support your pre-existing idea. Ignoring contrary evidence or focusing only on convenient patterns leads to the Texas Sharpshooter fallacy.</p>',
    pattern: '(\\b(cherry-picking\\s+data|ignoring\\s+the\\s+differences|focusing\\s+only\\s+on\\s+the\\s+similarities|finding\\s+a\\s+pattern\\s+after\\s+the\\s+fact)\\b)',
    url: 'https://en.wikipedia.org/wiki/Texas_sharpshooter_fallacy',
  },
  {
    id: 'special-pleading-029',
    name: 'Special Pleading',
    description: "<p>This fallacy involves applying rules or standards to others while making an unjustified exception for oneself or a particular case. It's like saying, \"The rules apply to everyone... except me (for no good reason).\"</p>",
    example: "<p>\"Everyone should pay their taxes on time, but I have a special situation so I don't need to, even though my situation isn't that different from others who do pay on time.\" This claims an exception without proper justification.</p>",
    recommendation: '<p>Apply rules and standards consistently. If you claim an exception for a particular case, ensure you have a valid and justifiable reason that distinguishes it, rather than just making a special plea.</p>',
    pattern: "(\\b(the\\s+rules\\s+don't\\s+apply\\s+to\\s+me|my\\s+case\\s+is\\s+different)\\s+because\\s+(I'm\\s+special|just\\s+because)\\b(?!.*\\b(with a valid, distinguishing reason)\\b))",
    url: 'https://en.wikipedia.org/wiki/Special_pleading',
  },
  {
    id: 'loaded-question-030',
    name: 'Loaded Question Fallacy',
    description: "<p>A loaded question is a question that contains a controversial or unjustified assumption, making it difficult to answer directly without appearing to agree with that assumption. It's a trick to trap someone.</p>",
    example: '<p>"Have you stopped cheating on your tests?" This question assumes the person has cheated in the past. Answering "yes" or "no" seems to admit to past cheating.</p>',
    recommendation: "<p>Avoid asking questions that sneak in unproven assumptions. If you're asked a loaded question, point out the unfair assumption within it before attempting to answer the intended query.</p>",
    pattern: '(\\b(have\\s+you\\s+stopped|are\\s+you\\s+still|why\\s+do\\s+you\\s+always)\\s+(.+)(\\?)\\b(?!.*\\b(when the presupposition is already established and accepted)\\b))',
    url: 'https://en.wikipedia.org/wiki/Loaded_question',
  },
  {
    id: 'middle-ground-fallacy-031',
    name: 'Middle Ground Fallacy (Argument to Moderation)',
    description: "<p>This fallacy assumes that the middle position between two extreme viewpoints must be the correct or best one. While compromise can be good, the truth doesn't always lie exactly in the middle.</p>",
    example: "<p>One person says the sky is always blue, another says the sky is never blue. Someone using the middle ground fallacy might conclude, \"Therefore, the sky is sometimes blue and sometimes not blue (e.g. at night), which must be the most reasonable view just because it's a compromise.\" While the conclusion might be true, it's not true *because* it's a middle point.</p>",
    recommendation: "<p>Don't assume a compromise is automatically correct. Evaluate each position based on its own evidence and logic, rather than just picking the middle point between two extremes.</p>",
    pattern: '(\\b(the\\s+truth|correct\\s+answer|best\\s+solution)\\s+must\\s+lie\\s+(somewhere\\s+in\\s+the\\s+middle|between\\s+the\\s+two\\s+extremes)\\b)',
    url: 'https://en.wikipedia.org/wiki/Argument_to_moderation',
  },
  {
    id: 'personal-incredulity-032',
    name: 'Personal Incredulity Fallacy',
    description: "<p>This fallacy occurs when someone concludes that because they find something difficult to understand or imagine, it must therefore be untrue or impossible. Lack of personal understanding isn't a valid reason to reject a concept.</p>",
    example: "<p>\"I can't imagine how a tiny seed can grow into a giant tree, so it must be impossible!\" Or, \"Quantum physics sounds too weird to be true, so I don't believe it.\" Personal difficulty in understanding doesn't disprove something.</p>",
    recommendation: "<p>Avoid dismissing an idea simply because you find it hard to grasp. Recognize that complex topics may require effort to understand, and your current level of understanding doesn't determine the truth of the matter.</p>",
    pattern: "(\\b(I\\s+can't\\s+understand|imagine|believe)\\s+how\\s+X\\s+could\\s+be\\s+true,\\s+so\\s+X\\s+must\\s+be\\s+false\\b|\\b(that's\\s+too\\s+complicated|weird\\s+to\\s+be\\s+true)\\b)",
    url: 'https://en.wikipedia.org/wiki/Argument_from_incredulity',
  },
  {
    id: 'appeal-to-wealth-033',
    name: 'Appeal to Wealth (Argumentum ad Crumenam)',
    description: "<p>This fallacy assumes that someone or something is better or more correct simply because they are wealthy, or that wealth is a measure of truth. Financial success doesn't equate to being right.</p>",
    example: "<p>\"This businessman is incredibly rich, so his opinions on politics must be very insightful and correct.\" His wealth doesn't automatically make his political views valid.</p>",
    recommendation: "<p>Don't assume that wealth makes someone's arguments or ideas inherently better or truer. Evaluate claims based on evidence and logic, not on the financial status of the person making them.</p>",
    pattern: "(\\b(he's|she's|they're)\\s+rich|wealthy|successful,\\s+so\\s+(he|she|they)\\s+must\\s+be\\s+(right|smart|correct)\\b|\\b(if\\s+you're\\s+so\\s+smart,\\s+why\\s+aren't\\s+you\\s+rich\\b.*when used to dismiss an argument))",
    url: 'https://en.wikipedia.org/wiki/Argumentum_ad_crumenam',
  },
  {
    id: 'appeal-to-poverty-034',
    name: 'Appeal to Poverty (Argumentum ad Lazarum)',
    description: "<p>This fallacy is the opposite of Appeal to Wealth; it assumes that someone or something is better or more virtuous simply because they are poor or less fortunate. Poverty doesn't automatically mean someone is right or more moral.</p>",
    example: "<p>\"This activist lives a very simple, poor life, so their ideas about how society should be run must be more pure and correct.\" Their financial status doesn't inherently validate their societal ideas.</p>",
    recommendation: "<p>Avoid assuming that poverty makes someone's arguments or character inherently better or more virtuous. Judge ideas and people on their merits, evidence, and actions, not their financial standing.</p>",
    pattern: "(\\b(he's|she's|they're)\\s+poor|humble|simple,\\s+so\\s+(he|she|they)\\s+must\\s+be\\s+(right|virtuous|more\\s+correct)\\b)",
    url: 'https://en.wikipedia.org/wiki/Argumentum_ad_lazarum',
  },
  {
    id: 'affirming-the-consequent-035',
    name: 'Affirming the Consequent',
    description: "<p>This is a formal fallacy where if you have a statement \"If A, then B,\" and B is true, you incorrectly conclude that A must also be true. Just because the consequence (B) happened doesn't mean the specific antecedent (A) was the cause.</p>",
    example: "<p>\"If it's raining (A), then the ground is wet (B). The ground is wet (B). Therefore, it must be raining (A).\" The ground could be wet for other reasons, like a sprinkler.</p>",
    recommendation: "<p>Be careful with \"if-then\" statements. If the 'then' part is true, don't automatically assume the 'if' part is true. There might be other causes for the consequence.</p>",
    pattern: '(\\b(if\\s+A\\s+then\\s+B\\.\\s+B\\s+is\\s+true\\.\\s+Therefore,\\s+A\\s+is\\s+true\\.)\\b|\\b(when\\s+it\\s+rains,\\s+the\\s+street\\s+gets\\s+wet\\.\\s+The\\s+street\\s+is\\s+wet,\\s+so\\s+it\\s+must\\s+have\\s+rained\\.)\\b(?!.*\\b(when A is the only cause of B)\\b))',
    url: 'https://en.wikipedia.org/wiki/Affirming_the_consequent',
  },
  {
    id: 'denying-the-antecedent-036',
    name: 'Denying the Antecedent',
    description: "<p>This is another formal fallacy with \"If A, then B\" statements. If A is not true, you incorrectly conclude that B must also not be true. The consequence (B) could still happen for other reasons even if A didn't occur.</p>",
    example: "<p>\"If it's raining (A), then the ground is wet (B). It is not raining (Not A). Therefore, the ground is not wet (Not B).\" The ground could still be wet from a sprinkler, even if it's not raining.</p>",
    recommendation: "<p>With \"if-then\" statements, if the 'if' part is false, don't automatically assume the 'then' part is also false. The consequence might still occur due to other factors.</p>",
    pattern: "(\\b(if\\s+A\\s+then\\s+B\\.\\s+Not\\s+A\\.\\s+Therefore,\\s+not\\s+B\\.)\\b|\\b(if\\s+you\\s+study,\\s+you'll\\s+pass\\.\\s+You\\s+didn't\\s+study,\\s+so\\s+you\\s+won't\\s+pass\\.)\\b(?!.*\\b(when A is the only condition for B)\\b))",
    url: 'https://en.wikipedia.org/wiki/Denying_the_antecedent',
  },
  {
    id: 'argument-by-repetition-037',
    name: 'Argument by Repetition (Argumentum ad Nauseam)',
    description: "<p>This fallacy involves repeating a claim over and over again until people start to accept it as true, often without any real evidence being presented. Repeating something doesn't make it factual.</p>",
    example: '<p>A commercial plays the same short jingle and slogan multiple times an hour, every day, hoping that by sheer repetition, people will start to believe the product is good or remember it when shopping.</p>',
    recommendation: "<p>Don't be swayed by how many times you hear a claim. Focus on the evidence and logical reasoning presented, not just the frequency of repetition, when deciding if something is true.</p>",
    pattern: "(\\b(repeating\\s+the\\s+same\\s+point|saying\\s+it\\s+over\\s+and\\s+over)\\s+(doesn't\\s+make\\s+it\\s+true|until\\s+people\\s+believe\\s+it)\\b)",
    url: 'https://en.wikipedia.org/wiki/Argumentum_ad_nauseam',
  },
  {
    id: 'appeal-to-fear-038',
    name: 'Appeal to Fear (Argumentum ad Metum/Baculum)',
    description: "<p>This fallacy tries to persuade by creating fear or threatening negative consequences if a certain action isn't taken or a belief isn't accepted. It relies on fear rather than logic or evidence.</p>",
    example: "<p>\"If you don't vote for this candidate, our country will fall into chaos and ruin!\" This tries to scare voters into supporting the candidate, rather than presenting logical reasons for their policies.</p>",
    recommendation: "<p>Be wary of arguments that try to scare you into agreement. While it's important to consider risks, decisions should be based on evidence and reason, not just fear of negative outcomes presented without proof.</p>",
    pattern: "(\\b(if\\s+you\\s+don't\\s+(do|believe)\\s+X,\\s+then\\s+something\\s+terrible|bad\\s+thing)\\s+will\\s+happen\\b|\\b(you\\s+must\\s+agree\\s+or\\s+face\\s+the\\s+consequences)\\b)",
    url: 'https://en.wikipedia.org/wiki/Appeal_to_fear',
  },
]

export const getFallacyById = (id: string): LogicalFallacy | undefined =>
  logicalFallaciesData.find(f => f.id === id)
